# Generated by Django 5.1.1 on 2025-11-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carrito", "0002_remove_carritoitem_carrito_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carrito_item",
            old_name="user",
            new_name="usuario",
        ),
    ]
