# Generated by Django 5.1.1 on 2024-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='static/IMAGES/producto.png', upload_to='static/product_image'),
        ),
    ]
